//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaiseTicket
    {
        public int Sno { get; set; }
        public string TicketNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public string Assigned_Person { get; set; }
        public string Query { get; set; }
        public string EmployeeId { get; set; }
        public string Issue_Type { get; set; }
        public string Status1 { get; set; }
        public string priarity { get; set; }
        public string Commant { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public string UpdateDate { get; set; }
    }
}
