//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsIT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRegister()
        {
            this.RaiseTickets = new HashSet<RaiseTicket>();
        }
    
        public System.Guid EmpID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string Password { get; set; }
        public string ResetpasswordCode { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<int> Firstregister { get; set; }
        public Nullable<int> registercount { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> Otp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaiseTicket> RaiseTickets { get; set; }
    }
}
